org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.5
fabric_version=0.141.3+1.21.11
command_api_version=2.4.7+6b42a6003e
rendering_version=16.2.10+0290ad933e

mod_version=1.0.0
maven_group=dev.novab.autismtv
archives_base_name=autismtv
